export { default as AuthenticationView } from './AuthenticationView'
export { default as DashboardView } from './DashboardView'
export { default as HistoryView } from './HistoryView'
export { default as AccountView } from './AccountView'
export { default as UserManagementView } from './UserManagementView'
export { default as TraderManagementView } from './TraderManagementView'